### ISSUE TITLE
No feature for register

### ISSUE THREAD

**Issue by sucahyana** [noviamarsheila/songkok-marwah-webapp#1]
izin clone

nanya dong ini feature registernya belum ada atau memang disengaja disembunyikan?
terus apa ini menggunakan laravel breeze jika iya kombinasi dengan apa ? livewire , react, vue, blade, next?
terima kasih bub

**Comment by noviamarsheila** [comment]
registernya sengaja lewat controller bub, karna hanya untuk admin saja

Pada Min, 14 Jul 2024 pukul 04.18 Sucahyana ***@***.***>
menulis:

**Comment by noviamarsheila** [comment]
tidak dikombinasikan apa", karna saya masih pemula :)

Pada Min, 14 Jul 2024 pukul 04.18 Sucahyana ***@***.***>
menulis:

**Comment by sucahyana** [comment]
oke bub makasih dah mantap
